---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-interviewer-config
  namespace: ai
  labels:
    app: ai-interviewer
data:
  SYSTEM_PROMPT: |
    You are Datavalley's AI Interviewer. Be concise and probing; follow STAR for behavioral questions.
  MODEL: "llama3.1:8b-instruct-q5_K_M"
  MAX_TOKENS: "512"
  TIMEOUT_MS: "60000"
  OLLAMA_BASE: "http://ollama:11434"
  STT_PROVIDER: "assemblyai"
  TTS_PROVIDER: "openai"
---
# Secret for bearer token and API keys
apiVersion: v1
kind: Secret
metadata:
  name: ai-interviewer-secret
  namespace: ai
type: Opaque
stringData:
  INTERNAL_KEY: "9d7h32Ghpq_!Bxm92JKj3kLvaL@8qYpf"
  JWT_SECRET: "e565bff47eb5a2ccc5f6d13645579d03e37bad51f81d356081db4fd3cee93ee4"
  MONGODB_URI: "mongodb+srv://ai_interviewer:Hyderabad123**@ai-interviewer-cluster.ctvdlak.mongodb.net/?retryWrites=true&w=majority"
  OPENAI_API_KEY: "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"
  ASSEMBLYAI_API_KEY: "2c829b4e2cfe405da5c2a1cd45cb8b75"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-interviewer
  namespace: ai
  labels:
    app: ai-interviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-interviewer
  template:
    metadata:
      labels:
        app: ai-interviewer
    spec:
      containers:
      - name: ai-interviewer
        image: asia-south1-docker.pkg.dev/datavalley-383814/ai-interviewer/ai-interviewer:v0.1.13
        ports:
        - containerPort: 8081
        env:
        - name: SYSTEM_PROMPT
          valueFrom:
            configMapKeyRef:
              name: ai-interviewer-config
              key: SYSTEM_PROMPT
        - name: MODEL
          valueFrom:
            configMapKeyRef:
              name: ai-interviewer-config
              key: MODEL
        - name: TIMEOUT_MS
          valueFrom:
            configMapKeyRef:
              name: ai-interviewer-config
              key: TIMEOUT_MS
        - name: MAX_TOKENS
          valueFrom:
            configMapKeyRef:
              name: ai-interviewer-config
              key: MAX_TOKENS
        - name: OLLAMA_BASE
          valueFrom:
            configMapKeyRef:
              name: ai-interviewer-config
              key: OLLAMA_BASE
        # Speech Service Configuration
        - name: STT_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: ai-interviewer-config
              key: STT_PROVIDER
        - name: TTS_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: ai-interviewer-config
              key: TTS_PROVIDER
        # API Keys from Secrets
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-secret
              key: OPENAI_API_KEY
        - name: ASSEMBLYAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-secret
              key: ASSEMBLYAI_API_KEY
        # Existing Secrets
        - name: INTERNAL_KEY
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-secret
              key: INTERNAL_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-secret
              key: JWT_SECRET
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: ai-interviewer-secret
              key: MONGODB_URI
        - name: PORT
          value: "8081"
        readinessProbe:
          httpGet:
            path: /v1/healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
# ClusterIP Service (for internal access)
apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer
  namespace: ai
spec:
  selector:
    app: ai-interviewer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: ClusterIP
---
# LoadBalancer Service (for external access)
apiVersion: v1
kind: Service
metadata:
  name: ai-interviewer-public
  namespace: ai
spec:
  selector:
    app: ai-interviewer
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
